services:
  app:
    image: ghcr.io/irsyamokta/intera:latest
    container_name: intera-app
    restart: always
    env_file:
      - .env
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - vite-build:/var/www/html/public/build
    networks:
      - dockernet

  web:
    image: nginx:alpine
    container_name: intera-nginx
    restart: always
    volumes:
      - vite-build:/var/www/html/public/build:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - app
    networks:
      - dockernet

volumes:
  vite-build:

networks:
  dockernet:
    external: true
